/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUNDstring = 1,
  anon_sym_POUNDlanguage = 2,
  anon_sym_POUNDlangdef = 3,
  anon_sym_POUNDinclude = 4,
  anon_sym_POUNDfont = 5,
  anon_sym_POUNDfontdef = 6,
  anon_sym_SLASH_EQ = 7,
  aux_sym_ctrlchar_directive_token1 = 8,
  sym_identifier = 9,
  sym_language_code = 10,
  sym_number = 11,
  sym_string = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym_string_directive = 15,
  sym_language_entry = 16,
  sym_langdef_directive = 17,
  sym_include_directive = 18,
  sym_font_directive = 19,
  sym_fontdef_directive = 20,
  sym_ctrlchar_directive = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_string_directive_repeat1 = 23,
  aux_sym_language_entry_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUNDstring] = "#string",
  [anon_sym_POUNDlanguage] = "#language",
  [anon_sym_POUNDlangdef] = "#langdef",
  [anon_sym_POUNDinclude] = "#include",
  [anon_sym_POUNDfont] = "#font",
  [anon_sym_POUNDfontdef] = "#fontdef",
  [anon_sym_SLASH_EQ] = "/=",
  [aux_sym_ctrlchar_directive_token1] = "control_char",
  [sym_identifier] = "identifier",
  [sym_language_code] = "language_code",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_string_directive] = "string_directive",
  [sym_language_entry] = "language_entry",
  [sym_langdef_directive] = "langdef_directive",
  [sym_include_directive] = "include_directive",
  [sym_font_directive] = "font_directive",
  [sym_fontdef_directive] = "fontdef_directive",
  [sym_ctrlchar_directive] = "ctrlchar_directive",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_directive_repeat1] = "string_directive_repeat1",
  [aux_sym_language_entry_repeat1] = "language_entry_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUNDstring] = anon_sym_POUNDstring,
  [anon_sym_POUNDlanguage] = anon_sym_POUNDlanguage,
  [anon_sym_POUNDlangdef] = anon_sym_POUNDlangdef,
  [anon_sym_POUNDinclude] = anon_sym_POUNDinclude,
  [anon_sym_POUNDfont] = anon_sym_POUNDfont,
  [anon_sym_POUNDfontdef] = anon_sym_POUNDfontdef,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [aux_sym_ctrlchar_directive_token1] = aux_sym_ctrlchar_directive_token1,
  [sym_identifier] = sym_identifier,
  [sym_language_code] = sym_language_code,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_string_directive] = sym_string_directive,
  [sym_language_entry] = sym_language_entry,
  [sym_langdef_directive] = sym_langdef_directive,
  [sym_include_directive] = sym_include_directive,
  [sym_font_directive] = sym_font_directive,
  [sym_fontdef_directive] = sym_fontdef_directive,
  [sym_ctrlchar_directive] = sym_ctrlchar_directive,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_directive_repeat1] = aux_sym_string_directive_repeat1,
  [aux_sym_language_entry_repeat1] = aux_sym_language_entry_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUNDstring] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDlanguage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDlangdef] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDfont] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDfontdef] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_ctrlchar_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_language_code] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_language_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_langdef_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_font_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_fontdef_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_ctrlchar_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_language_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_char = 1,
  field_code = 2,
  field_description = 3,
  field_id = 4,
  field_name = 5,
  field_path = 6,
  field_size = 7,
  field_styles = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_char] = "char",
  [field_code] = "code",
  [field_description] = "description",
  [field_id] = "id",
  [field_name] = "name",
  [field_path] = "path",
  [field_size] = "size",
  [field_styles] = "styles",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_id, 1},
  [2] =
    {field_char, 1},
  [3] =
    {field_name, 1},
  [4] =
    {field_code, 1},
    {field_description, 2},
  [6] =
    {field_code, 1},
  [7] =
    {field_id, 1},
    {field_name, 2},
    {field_size, 3},
    {field_styles, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      if (lookahead == '#') ADVANCE(48);
      if (lookahead == '/') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(84);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(84);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(7);
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(42);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 34:
      if (eof) ADVANCE(36);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_POUNDstring);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUNDlanguage);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_POUNDlangdef);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUNDinclude);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_POUNDfont);
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_POUNDfontdef);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_ctrlchar_directive_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_ctrlchar_directive_token1);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_ctrlchar_directive_token1);
      if (lookahead == '/') ADVANCE(84);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_ctrlchar_directive_token1);
      if (lookahead == '/') ADVANCE(84);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_ctrlchar_directive_token1);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(7);
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_ctrlchar_directive_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_language_code);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(84);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 34},
  [11] = {.lex_state = 34},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 34},
  [16] = {.lex_state = 34},
  [17] = {.lex_state = 34},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 34},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 34},
  [23] = {.lex_state = 34},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 34},
  [26] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUNDstring] = ACTIONS(1),
    [anon_sym_POUNDlanguage] = ACTIONS(1),
    [anon_sym_POUNDlangdef] = ACTIONS(1),
    [anon_sym_POUNDinclude] = ACTIONS(1),
    [anon_sym_POUNDfont] = ACTIONS(1),
    [anon_sym_POUNDfontdef] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [aux_sym_ctrlchar_directive_token1] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_language_code] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym_string_directive] = STATE(2),
    [sym_langdef_directive] = STATE(2),
    [sym_include_directive] = STATE(2),
    [sym_font_directive] = STATE(2),
    [sym_fontdef_directive] = STATE(2),
    [sym_ctrlchar_directive] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDstring] = ACTIONS(7),
    [anon_sym_POUNDlangdef] = ACTIONS(9),
    [anon_sym_POUNDinclude] = ACTIONS(11),
    [anon_sym_POUNDfont] = ACTIONS(13),
    [anon_sym_POUNDfontdef] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_string_directive] = STATE(3),
    [sym_langdef_directive] = STATE(3),
    [sym_include_directive] = STATE(3),
    [sym_font_directive] = STATE(3),
    [sym_fontdef_directive] = STATE(3),
    [sym_ctrlchar_directive] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_POUNDstring] = ACTIONS(7),
    [anon_sym_POUNDlangdef] = ACTIONS(9),
    [anon_sym_POUNDinclude] = ACTIONS(11),
    [anon_sym_POUNDfont] = ACTIONS(13),
    [anon_sym_POUNDfontdef] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_string_directive] = STATE(3),
    [sym_langdef_directive] = STATE(3),
    [sym_include_directive] = STATE(3),
    [sym_font_directive] = STATE(3),
    [sym_fontdef_directive] = STATE(3),
    [sym_ctrlchar_directive] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_POUNDstring] = ACTIONS(23),
    [anon_sym_POUNDlangdef] = ACTIONS(26),
    [anon_sym_POUNDinclude] = ACTIONS(29),
    [anon_sym_POUNDfont] = ACTIONS(32),
    [anon_sym_POUNDfontdef] = ACTIONS(35),
    [anon_sym_SLASH_EQ] = ACTIONS(38),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_POUNDfont,
    ACTIONS(45), 1,
      sym_string,
    STATE(7), 1,
      aux_sym_language_entry_repeat1,
    ACTIONS(41), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlanguage,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [22] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_POUNDlanguage,
    ACTIONS(51), 1,
      anon_sym_POUNDfont,
    STATE(6), 2,
      sym_language_entry,
      aux_sym_string_directive_repeat1,
    ACTIONS(47), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [44] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_POUNDlanguage,
    ACTIONS(58), 1,
      anon_sym_POUNDfont,
    STATE(6), 2,
      sym_language_entry,
      aux_sym_string_directive_repeat1,
    ACTIONS(53), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [66] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_POUNDfont,
    ACTIONS(64), 1,
      sym_string,
    STATE(7), 1,
      aux_sym_language_entry_repeat1,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlanguage,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [88] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_POUNDfont,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_POUNDfont,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [118] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_POUNDfont,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [133] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_POUNDfont,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [148] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_POUNDfont,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      anon_sym_POUNDstring,
      anon_sym_POUNDlangdef,
      anon_sym_POUNDinclude,
      anon_sym_POUNDfontdef,
      anon_sym_SLASH_EQ,
  [163] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_POUNDlanguage,
    STATE(5), 2,
      sym_language_entry,
      aux_sym_string_directive_repeat1,
  [174] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym_string,
    STATE(4), 1,
      aux_sym_language_entry_repeat1,
  [184] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
  [191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
  [198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_string,
  [205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_language_code,
  [212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_identifier,
  [219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_ctrlchar_directive_token1,
  [233] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_string,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_number,
  [247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_string,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_string,
  [261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_language_code,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 22,
  [SMALL_STATE(6)] = 44,
  [SMALL_STATE(7)] = 66,
  [SMALL_STATE(8)] = 88,
  [SMALL_STATE(9)] = 103,
  [SMALL_STATE(10)] = 118,
  [SMALL_STATE(11)] = 133,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 163,
  [SMALL_STATE(14)] = 174,
  [SMALL_STATE(15)] = 184,
  [SMALL_STATE(16)] = 191,
  [SMALL_STATE(17)] = 198,
  [SMALL_STATE(18)] = 205,
  [SMALL_STATE(19)] = 212,
  [SMALL_STATE(20)] = 219,
  [SMALL_STATE(21)] = 226,
  [SMALL_STATE(22)] = 233,
  [SMALL_STATE(23)] = 240,
  [SMALL_STATE(24)] = 247,
  [SMALL_STATE(25)] = 254,
  [SMALL_STATE(26)] = 261,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_language_entry, 3, 0, 6),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_language_entry, 3, 0, 6),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_directive, 3, 0, 4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_directive, 3, 0, 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_directive_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_directive_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_language_entry_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_language_entry_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_language_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 2, 0, 1),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_directive, 2, 0, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_font_directive, 2, 0, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_font_directive, 2, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_langdef_directive, 3, 0, 5),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_langdef_directive, 3, 0, 5),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fontdef_directive, 5, 0, 7),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fontdef_directive, 5, 0, 7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctrlchar_directive, 2, 0, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ctrlchar_directive, 2, 0, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_uni(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "uni",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
